### ISSUE TITLE
Menschenfeindlichkeit

### ISSUE THREAD

**Issue by nuIIpointerexception** [yohzu/aaronstinker#2]
Das ist schon sehr diskriminierend dass du den Namen "aaron" für diese repository benutzt!

**Comment by NeuroException** [comment]
@yohzu  Akzeptiere diese antwort

**Comment by NeuroException** [comment]
anzeige is raus

**Comment by nuIIpointerexception** [comment]
ist so!

**Comment by nuIIpointerexception** [comment]
Was soll das 🌵

**Comment by NeuroException** [comment]
Es wird gemunkelt, dass man ein achievement bekommt, wenn man etwas mit nem herz reacted
